### PR TITLE
Enforcing sentencepiece version to be 0.1.91

### PR DESCRIPTION
**Pull request by AbdallahNasir**
The latest sentence piece version generates errors when installed.

### CODE REVIEW

**Comment by owo** [comment]
Hi @AbdallahNasir 

Can you please tell me more about which Python version, OS, etc you are using?
I just did a fresh install of camel-tools on my mac (python 3.6) which downloaded sentencepiece v0.1.94 and everything worked.
Also, can you please paste the error log that you get so we can narrow down the cause of the error.

**Comment by AbdallahNasir** [comment]
Hi @owo ,

Please check https://github.com/google/sentencepiece/issues/594 , It has got the logs and everything you may need. It is not an issue from your side, but theirs.

**Comment by owo** [comment]
Thanks!
For now, I'll keep this PR on hold but I'll be monitoring that thread and experimenting on an Ubuntu 18 LTS VM to see if I can replicate the problem.
If I do get the same results, I'll comment on the sentencepiece issue to substantiate it.

**Comment by AbdallahNasir** [comment]
The issue was because of an outdated pip, no need for you to do anything. 

Thanks,

Best wishes,

**Pull request closed without merging**
