### PR TITLE
Elongation Removal for Normalizing Arabic Text

### PR DESCRIPTION
**Pull request by balhafni**
I was normalizing some data and I think that having an elongation removal functionality as part of the `utils.normalize` could be useful :smile: and I added this in `remove_elongation()`

### CODE REVIEW

**Comment by owo** [comment]
This sounds like a great addition! However, here are few things you might want to consider:

1) There are legitimate cases where two duplicates appear consecutively (eg. مميز، الله). As far as I can tell, allowing up to two consecutive duplicates is the best policy for a regex-based approach.
2) It would also be best to precompile the regex objects to keep things efficient (you can see examples of this in the same file such as the normalize_alef functions).
3) I think this shouldn't apply to numbers or punctuation. Perhaps this could even include foreign words, if not using a transliteration scheme? If that's the case then we would need ar, bw, safebw, xmlbw, and hsb variants of this function (see the normalize_alef variants). To do so, your regexes must explicitly use the appropriate set from [camel_tools.utils.charsets](https://github.com/CAMeL-Lab/camel_tools/blob/b738e328c9ac2cfe21e0d13e9f77702f970c79f6/camel_tools/utils/charsets.py). You can see an example of this for diacritics [here](https://github.com/CAMeL-Lab/camel_tools/blob/b738e328c9ac2cfe21e0d13e9f77702f970c79f6/camel_tools/utils/dediac.py#L39).
4) Perhaps a less ambiguous name might be needed as to not confuse it with [Arabic tatweel](https://www.fileformat.info/info/unicode/char/0640/index.htm) which has the effect of elongating words when rendered. If you have some other name suggestions, please let me know.
5) This approach will not work well if the duplicated text is diacritized. I don't necessarily think this should be addressed in a simple function like this, but it is worth mentioning in the documentation. If we are to address it though, the question we need to answer is which diacritics do we keep?

**Comment by slkh** [comment]
Thanks Bashar and Ossama

I would like to add an extra piece of information regarding Ossama's comments.
In this [paper](https://www.aclweb.org/anthology/N13-1066), specifically in section 6.1, you would find more about how they are handling **"Speech Effect"** in raw dialectal text.

**Comment by balhafni** [comment]
I found the [paper](https://www.aclweb.org/anthology/L16-1640) we talked about today in the meeting. The approach they took to reduce repeated characters was to analyze ~392M Egyptian words and pick top 400 repeated types and see how much they contributed to tokens with repeated characters. The conclude that `371` types (73%) have repetitions that are reduced into a single letter, while the rest `29` (7%) have repetitions that are either reduced into two letters or special cases.

So they decided to reduce all the repeated characters to a single character and created a lookup table for the `29` special cases. They also use the term `elongation` vs `repetition` interchangeably  :smiley_cat: :smiley_cat: :smile_cat:

**Comment by balhafni** [comment]
I added the policy functionality that we discussed yesterday. The user now have the option to indicate how the repeated characters should be reduced by specifying the policy. If `policy=1` the repeated instances will be reduced to `1` character. Otherwise if `policy=2`, the repeated instances will be reduced to `2` characters. The default option is reducing to `1` character. If a different value other than `1` or `2` is specified, an error is raised indicating this.

**Pull request closed without merging**
